In [1]:
import numpy as np


In [2]:
data = np.loadtxt("/Users/praveenallam/Downloads/fit.txt", dtype = "str")

In [7]:
data.shape

(96, 6)

In [4]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [17]:
date, steps_count, mood, calories_burned, hours_slept, activity_status = data.T

In [18]:
date.shape

(96,)

In [19]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [14]:
steps_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [20]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [21]:
hours_slept

array(['5', '8', '5', '4', '5', '6', '6', '7', '5', '6', '8', '5', '6',
       '7', '5', '6', '8', '5', '4', '5', '6', '8', '5', '6', '5', '8',
       '5', '4', '5', '4', '5', '4', '3', '2', '9', '5', '6', '4', '5',
       '8', '4', '5', '6', '5', '6', '5', '6', '5', '6', '5', '6', '7',
       '6', '7', '6', '5', '6', '7', '8', '8', '7', '8', '5', '4', '3',
       '3', '4', '5', '5', '5', '3', '4', '4', '5', '5', '5', '5', '5',
       '5', '4', '3', '4', '5', '5', '4', '5', '3', '3', '3', '2', '3',
       '2', '8', '5', '5', '5'], dtype='<U10')

In [22]:
activity_status

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [23]:
hours_slept = np.array(hours_slept, dtype = "int")

In [24]:
hours_slept

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [25]:
steps_count = np.array(steps_count, dtype = "int")

In [26]:
steps_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [28]:
max_step_count = np.max(steps_count)
max_step_count

7422

In [29]:
min_step_count = np.min(steps_count)
min_step_count

25

In [31]:
date_on_max_step_count = date[np.argmax(steps_count)]
date_on_max_step_count

'14-12-2017'

In [32]:
date_on_min_step_count = date[np.argmin(steps_count)]
date_on_min_step_count

'08-10-2017'

In [34]:
step_count_avg = steps_count.mean()
step_count_avg

2935.9375

In [35]:
mood_check = mood[steps_count < step_count_avg]
mood_check

array(['Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Neutral',
       'Neutral', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy'], dtype='<U10')

In [37]:
np.unique(mood_check, return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([16, 13, 19]))

In [38]:
np.unique(mood, return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))

In [39]:
np.unique(mood[steps_count < 1000], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([10,  5, 13]))

In [40]:
np.unique(mood[steps_count < 2000], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([13,  8, 18]))

In [41]:
np.unique(mood[steps_count < 2500], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([15, 11, 18]))

In [42]:
np.unique(mood[steps_count < 3000], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([16, 13, 19]))

In [43]:
np.unique(mood[steps_count < 3500], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([17, 15, 20]))

In [44]:
np.unique(mood[steps_count < 4000], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([18, 18, 22]))

In [45]:
np.unique(mood[steps_count < 5000], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([31, 22, 26]))

In [46]:
np.unique(mood[steps_count < 4500], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([26, 21, 24]))

In [53]:
min_hours_slept = np.min(hours_slept)
min_hours_slept

2

In [54]:
max_hours_slept = np.max(hours_slept)
max_hours_slept

9

In [48]:
sleep_mean = np.mean(hours_slept)
sleep_mean

5.21875

In [49]:
np.unique(mood[hours_slept < sleep_mean], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([20, 24, 19]))

In [50]:
np.unique(mood[hours_slept >= sleep_mean], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([20,  3, 10]))

In [51]:
np.unique(mood[hours_slept < 3], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([1, 1, 1]))

In [55]:
np.unique(mood[hours_slept < 4], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([1, 5, 6]))

In [56]:
np.unique(mood[hours_slept > 7 ], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([7, 1, 3]))

In [57]:
np.unique(mood[hours_slept > 6], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([10,  2,  5]))

In [59]:
np.unique(activity_status, return_counts = True)

(array(['Active', 'Inactive'], dtype='<U10'), array([42, 54]))

In [60]:
active = activity_status == 'Active'

In [67]:
sleep_hours_active = hours_slept[active]
sleep_hours_active

array([5, 6, 8, 5, 6, 4, 5, 8, 4, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8,
       7, 8, 5, 3, 3, 5, 5, 5, 3, 4, 5, 5, 5, 5, 4, 5, 5, 4, 5, 5])

In [62]:
np.unique(sleep_hours_active, return_counts = True)

(array([3, 4, 5, 6, 7, 8]), array([ 3,  5, 18,  7,  4,  5]))

In [68]:
sleep_hours_inactive = hours_slept[~active]
sleep_hours_inactive

array([5, 8, 5, 4, 6, 6, 7, 5, 6, 8, 5, 7, 5, 6, 8, 5, 4, 5, 6, 8, 5, 6,
       5, 5, 4, 5, 4, 4, 3, 2, 9, 5, 5, 6, 5, 6, 5, 6, 4, 4, 4, 5, 5, 4,
       3, 5, 3, 3, 3, 2, 3, 2, 8, 5])

In [65]:
np.unique(sleep_hours_inactive, return_counts = True)

(array([2, 3, 4, 5, 6, 7, 8, 9]), array([ 3,  6,  9, 19,  9,  2,  5,  1]))

In [66]:
np.unique(activity_status[hours_slept > 7], return_counts = True)

(array(['Active', 'Inactive'], dtype='<U10'), array([5, 6]))

In [69]:
np.unique(activity_status[hours_slept < 5], return_counts = True)

(array(['Active', 'Inactive'], dtype='<U10'), array([ 8, 18]))

In [70]:
np.unique(activity_status[hours_slept == 5], return_counts = True)

(array(['Active', 'Inactive'], dtype='<U10'), array([18, 19]))

In [73]:
np.unique(activity_status[(hours_slept == 5) & (steps_count < 2500)], return_counts = True)

(array(['Active', 'Inactive'], dtype='<U10'), array([5, 9]))

In [75]:
steps_count[hours_slept==5].mean()

3272.162162162162

In [76]:
steps_count[hours_slept==5].max()

7422

In [77]:
steps_count[hours_slept==5].min()

25

In [78]:
np.unique(activity_status[(hours_slept == 5) & (steps_count < 3272.162162162162)], return_counts = True)

(array(['Active', 'Inactive'], dtype='<U10'), array([ 6, 10]))

In [79]:
np.unique(activity_status[(hours_slept == 5) & (steps_count > 3272.162162162162)], return_counts = True)

(array(['Active', 'Inactive'], dtype='<U10'), array([12,  9]))

In [80]:
np.unique(activity_status[(hours_slept == 5) & (steps_count > 5000)], return_counts = True)

(array(['Active', 'Inactive'], dtype='<U10'), array([5, 2]))

In [85]:
np.unique(activity_status[(hours_slept >= 5) & (steps_count > 5000)], return_counts = True)

(array(['Active', 'Inactive'], dtype='<U10'), array([8, 5]))