In [4]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
type(a)

numpy.ndarray

In [9]:
a.dtype

dtype('int64')

In [10]:
%timeit a**2

446 ns ± 4.43 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
b = [1,2,3,4]

In [14]:
c = [i**2 for i in b]
c

[1, 4, 9, 16]

In [13]:
%timeit [i**2 for i in b]

867 ns ± 5.97 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [16]:
%timeit range(0,100000)

132 ns ± 0.85 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [18]:
%timeit np.arange(0,100000)

18.2 µs ± 429 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [22]:
np.arange(100,1,-4.5)

array([100. ,  95.5,  91. ,  86.5,  82. ,  77.5,  73. ,  68.5,  64. ,
        59.5,  55. ,  50.5,  46. ,  41.5,  37. ,  32.5,  28. ,  23.5,
        19. ,  14.5,  10. ,   5.5])

In [23]:
np.round(np.arange(1,11,0.333),2)

array([ 1.  ,  1.33,  1.67,  2.  ,  2.33,  2.66,  3.  ,  3.33,  3.66,
        4.  ,  4.33,  4.66,  5.  ,  5.33,  5.66,  5.99,  6.33,  6.66,
        6.99,  7.33,  7.66,  7.99,  8.33,  8.66,  8.99,  9.32,  9.66,
        9.99, 10.32, 10.66, 10.99])

In [24]:
np.arange(1,11,0.333)

array([ 1.   ,  1.333,  1.666,  1.999,  2.332,  2.665,  2.998,  3.331,
        3.664,  3.997,  4.33 ,  4.663,  4.996,  5.329,  5.662,  5.995,
        6.328,  6.661,  6.994,  7.327,  7.66 ,  7.993,  8.326,  8.659,
        8.992,  9.325,  9.658,  9.991, 10.324, 10.657, 10.99 ])

In [25]:
d = np.array([1,2,3,4.0])
d

array([1., 2., 3., 4.])

In [26]:
d = np.array([1,2,3,4.0, 'Fuck'])
d

array(['1', '2', '3', '4.0', 'Fuck'], dtype='<U32')

In [29]:
d = np.array([1,2,3,4.0,'Fuck', True])
d

array(['1', '2', '3', '4.0', 'Fuck', 'True'], dtype='<U32')

In [43]:
d = np.linspace(1,7,num = 3).astype(int)
d

array([1, 4, 7])

In [44]:
d = np.linspace(1,7,10).astype(int)
d

array([1, 1, 2, 3, 3, 4, 5, 5, 6, 7])

In [45]:
d = np.linspace(1,7,10)
d

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])